### ISSUE TITLE
FPGA board support

### ISSUE THREAD

**Issue by kingstone1927** [rafaelcalcada/steel-core#2]
does this core support the Zedboard - FPGA? Thanks in advance

**Comment by rafaelcalcada** [comment]
Hi Thach,

Steel was developed and tested on Xilinx FPGAs. Although it has not been tested on a Zedboard, I believe that there should be no problems when synthesizing Steel on this board - if you face any problem, you can open a new issue here so I can help you to solve it. ;)

Rafael.

**Comment by kingstone1927** [comment]
@rafaelcalcada  Thank you, I started a new issue. I hope you can help me.

**Comment by rafaelcalcada** [comment]
Great! I'm closing this issue :)
