### ISSUE TITLE
Vector mode (mtvec)

### ISSUE THREAD

**Issue by Kefir0192** [rafaelcalcada/steel-core#4]
Looking through the code here's what I found, Steel-Core strange behavior in the TRAP vector processing mode.

Assuming that the TRAP_TAKEN signal becomes true in stage (2) of the decoding:

```
assign TRAP_TAKEN = (MIE & ip) | exception | ecall | break;
```

Here's what's going to happen.

1. State machine, on the next rising edge of clk, will transition from the STATE_OPERATING stage to the STATE_TRAP_TAKEN stage.

   Where FLUSH, SET_EPC and SET_CAUSE will be set to true, and the next instruction fetch address will be PC_TRAP (aka TRAP_ADDRESS, aka MTVEC):
```
PC_SRC = `PC_TRAP;
FLUSH = 1'b1;
SET_EPC = 1'b1;
SET_CAUSE = 1'b1;
```

   And the NOP instruction will enter the decoding stage.

2. On the next rising clk edge, the automaton will transition from the STATE_TRAP_TAKEN stage to the STATE_OPERATING stage.

    The MEPC register will be written to the PC value to return from TRAP.
    Will be written to the CAUSE register TRAP cause values.
    The instruction will be fetched (instruction memory read) at the MTVEC address and the selected instruction will go to the decoding stage.

But. If vector mode is enabled, the MODE bits in the MTVEC register are 01.
Then the TRAP processing address must refer to "BASE + 4 x cause", but the MCAUSE entry was made on the current rising edge of clk.
This means that instruction fetching (reading the instruction memory) is done using the old MCAUSE value.

Perhaps I made a mistake somewhere, I ask for your attention.

**Comment by rafaelcalcada** [comment]
Hi @Kefir0192, you're right, Steel is taking the old value of MCAUSE in Vector Mode, which is wrong. Tomorrow I'll push a fix to it.

Thanks for your contribution!
